# Generated by Django 2.1 on 2019-10-14 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttcontrib', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='c_url',
            field=models.URLField(default=-2018),
            preserve_default=False,
        ),
    ]
